### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by DonRichards** [mjordan/islandora_workbench#200] opened 2021-01-14 19:54 UTC
Lol. I’m seeing something interesting that might be a bug. 

Create an error, fix the error and it doesn’t pickup the correction
I added `subject:Pink|subject:Flowers` to the __field_subject__ 

<img width="1568" alt="Screen Shot 2021-01-14 at 2 42 00 PM" src="https://user-images.githubusercontent.com/2738244/104641062-48f45080-5677-11eb-9e7f-618a6582e621.png">

[My Google sheet](https://docs.google.com/spreadsheets/d/1u9Jc6yC21p1je1SqiO7Fm_jliUo09K38dl7bjJAo0Bs/edit?usp=sharing)

## To replicate Error
* Add `subject:Pink|subject:Flowers` to the __field_subject__ 
* Run `./workbench --config hackdoc_demo.yml --check`
* Remove `subject:Pink|subject:Flowers` to the __field_subject__ 
* Run `./workbench --config hackdoc_demo.yml --check`

May not be related but I tried to run it without the check.

**Comment by mjordan** [comment] 2021-01-14 20:06
Duplicate of #202.

**Closed by mjordan** 2021-01-14 20:06 UTC
