### ISSUE TITLE
Workbench says custom Typed Relation field has more than one value but it doesn't, then node is not created with error 422

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#356] opened 2021-11-22 16:14 UTC
I am ingesting a CSV into a Drupal 9 site (9.4.0-dev), with what I believe is the most up-to-date version of Workbench and the Workbench Integration module. For several objects, I saw an error message like this:
`19-Nov-21 13:20:38 - WARNING - Adding all values in CSV field field_primary_creator for record islandora:trc_2715 would exceed maximum number of allowed values (1), so only adding first value.`
And then the object was not created:
`19-Nov-21 13:20:38 - ERROR - Node for CSV record islandora:trc_2715 not created, HTTP response code was 422.`
When I look at the CSV, there is only one value in the field_primary_creator column for these objects - one example:
`relators:cre:corporate_body:Scholten & Baijings (Firm)`
Another example:
`"relators:aut:person:Laubin, Reginald"`

When I switch my Primary Creator field to being multivalue, the ingest completes successfully. However, the client wants this to be a single value field.

Here's what I have after pulling from main this morning:

```
 * branch            main       -> FETCH_HEAD
   bb551a1..d072d94  main       -> origin/main
Updating 0f1a926..d072d94
```

Attached is my CSV and the log file. I can't figure out why Workbench thinks there is more than one value in the field_primary_creator column. Additionally, when it doesn't create the object, the following objects within that compound set don't get their url_alias values applied. So somewhere there must be an extra comma or value throwing this off, but I can't find it.

[IngestTestPrimaryCreators.csv](https://github.com/mjordan/islandora_workbench/files/7582518/IngestTestPrimaryCreators.csv)
[PrimaryCreatorErrors.log](https://github.com/mjordan/islandora_workbench/files/7582621/PrimaryCreatorErrors.log)

**Comment by mjordan** [comment] 2021-11-23 04:41
@dara2 I have fixed the issue with the single-valued typed relation field. Can you please pull down updates to `main` and test?

> Additionally, when it doesn't create the object, the following objects within that compound set don't get their url_alias values applied.

This is a separate problem which I will open a new issue for.

**Comment by dara2** [comment] 2021-11-23 13:39
That's AWESOME - thank you, Mark! I'll test it today.

**Comment by dara2** [comment] 2021-11-24 20:45
This worked, thank you!

**Comment by mjordan** [comment] 2021-11-24 20:49
Super, thanks for testing. I'm working with someone else in slack to figure out if that fix solved their problem (which may not be the same problem, don't know yet). Glad to hear it worked for you. I'm going to close this assuming that the other problem is caused by something else.

**Closed by mjordan** 2021-11-24 20:49 UTC
Labels: bug, taxonomies
