### ISSUE TITLE
`url_alias` field population fails if no `file` field specified within a CSV input row

### ISSUE THREAD

**Issue by jefferya** [mjordan/islandora_workbench#703] opened 2023-10-25 20:49 UTC
When using Workbench to create new nodes, all with an `url_alias` specified in the input CSV, I found some resulting Drupal Islandora nodes without a corresponding URL alias registered in Drupal. In the workbench.log, there was no `/entity/path_alias` record for those nodes missing the URL alias. The commonality between the failures appears to be an empty `file` field in the CSV row (as one would expect when the row is a collection).

The `continue` in the following code block appears to cause the skipping of the `create_url_alias` function call (and thus the lack of a URL alias in Drupal)

https://github.com/mjordan/islandora_workbench/blob/f41fa85b0afac02c9a6adc9d92c1a8355624f8cd/workbench#L318-L322

I'm testing a fix that would see move the `create_url_alias` function call above the aforementioned block.

To reproduce:

* Islandora Workbench commit f41fa85b0afac02c9a6adc9d92c1a8355624f8cd
* create a CSV input file with a row containing the required fields, empty `file` field, and `url_alias` field filled in
* check `/admin/config/search/path`

**Comment by mjordan** [comment] 2023-10-25 20:51
@jefferya thanks for finding this. Please open a PR when you have one.

**Comment by jefferya** [comment] 2023-10-25 21:12
I'm not sure if my PR has any side effects. I've only looked in the context of the `task: create` workflow.

**Comment by mjordan** [comment] 2023-10-30 04:21
Merged with 3c3f7a8d8a12b9936cb8a41df77a401bb9f493b2. Thanks for finding and fixing this!

**Comment by dara2** [comment] 2023-11-15 19:29
Hi @mjordan - Adding this here from Slack, as it could be related to the recent PR for this issue:
> Has anyone had a url_alias fail to be made during Workbench ingest only for a certain type of object? We have a strange situation where url_alias gets added on ingest for Page objects (Model=Page), but not for Paged Content (their parent objects, Model=Paged Content) during the same ingest. When we run a Workbench update task to add the alias later, it is added successfully. We’ve disabled path alias patterns on the site, and are just using what comes in through the Workbench CSV’s url_alias column. This only started happening in mid-October (wasn’t a problem previously). So I’m not sure if it somehow something in our code, or what. I thought I would check and see if anyone has seen this behavior before.

**Comment by mjordan** [comment] 2023-12-06 15:08
@dara2 how are you creating pages, using the "with page/child-level metadata" method or using the using subdirectories" method? I assume using the former but I wanted to confirm before trying to replicate.

**Comment by dara2** [comment] 2024-01-17 21:00
I think this should be reopened? I don't think the issue we ran into and reported (https://github.com/mjordan/islandora_workbench/issues/703#issuecomment-1813132852) was resolved?

**Comment by mjordan** [comment] 2024-01-18 00:28
Hi @dara2 I'll tackle this one next.

**Comment by mjordan** [comment] 2024-01-18 04:03
@dara2 @dmer I'm trying to replicate the problem and can't (all new nodes get URL aliass), using the config and csv below. Can you try these and let me know what happens?

```
task: create
host: https://islandora.traefik.me
username: admin
password: password
input_csv: issue_703.csv
nodes_only: true
```
```
id,parent_id,field_weight,file,title,field_model,field_member_of,url_alias
001,,,,Issue 703 parent 1,Paged Content,,/issue_703_1
003,001,1,,Issue 703 1 page 1,Page,,/issue_703_2
004,001,2,,Issue 703 1 page 2,Page,,/issue_703_3
002,,,,Issue 703 parent 2,Paged Content,,/issue_703_4
006,002,1,,Issue 703 2 page 1,Page,,/issue_703_5
007,002,2,,Issue 703 2 page 2,Page,,/issue_703_6
```

**Comment by dara2** [comment] 2024-01-18 13:35
I'll see if Derek can share the config and part of a CSV he was using when he got this problem yesterday (and check which version of WB he's on).

**Comment by dmer** [comment] 2024-01-18 14:54
Hi @mjordan - I re-tested my set that had the missing URL alias issue after I found that the WB install on that server was not up-to-date. I pulled the latest Main and now (unlike before) the records with no values in the file field received their correct URL alias as expected.  So, with a latest WB I cannot reproduce this issue.

**Comment by mjordan** [comment] 2024-01-18 15:04
OK, super, that is consistent with my experience last night. Can I reclose this issue?

**Comment by dara2** [comment] 2024-01-18 15:07
That's fine with me!

**Closed** 2024-01-18 15:16 UTC
Labels: bug
