### ISSUE TITLE
EDTF validation

### ISSUE THREAD

**Issue by ajstanley** [mjordan/islandora_workbench#264] opened 2021-05-06 19:54 UTC
Some valid EDTF entries are failing validation -
1919-04-23~/1919-04-25~
1910~
Both of these dates work when entered into an EDTF date field through the user interface

**Comment by seth-shaw-unlv** [comment] 2021-05-06 19:57
I believe these are both valid values. Intervals and single years can both have approximate signifiers.

**Comment by mjordan** [comment] 2021-05-06 20:33
Thanks, I'll take a look.

**Comment by ajstanley** [comment] 2021-05-06 20:56
I've just deleted 
```
        if len(parts) == 3 and re.search(r'\?|~', parts[2]):
            return False, 'Invalid date qualifier in "' + parts[2] + ", must be a %."
			
        if parts[0] is not None and re.search('~|%', parts[0]):
            return False, 'Invalid date qualifier in "' + parts[0] + ", must be a ?."
```
and it works as intended.

**Comment by mjordan** [comment] 2021-05-07 13:50
We still want validation on those. I'll take a look over the weekend, including adding unit tests for the samples above. If you guys have additional samples, please share them and I'll add them to the tests.

**Comment by seth-shaw-unlv** [comment] 2021-05-07 15:59
If you want to use someone else's EDTF code, there is [a Python EDTF library](https://pypi.org/project/edtf/). Pass the EDTF string into the parse function and an invalid EDTF string will throw a EDTFParseException.

**Comment by mjordan** [comment] 2021-05-08 17:06
@seth-shaw-unlv thanks, that library looks very useful. One question - if I use it to validate ETDF values in CSV, is there a risk that the data would pass validation but be valid for a feature of ETDF that the Drupal module doesn't support? In other words, date fields populated by Workbench might not work in Drupal because the data in those fields is not yet supported in the Drupal module. Should we worry about this?

**Comment by seth-shaw-unlv** [comment] 2021-05-09 00:51
I think we have feature parity, so it should be fine. The only potential issue is that the widget can restrict EDTF features which would force someone manually editing the item to comply with widget settings before saving it again.

**Comment by mjordan** [comment] 2021-08-31 04:28
@seth-shaw-unlv looks like your tests for "[1900-31](https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/tests/src/Kernel/EdtfUtilsTest.php#L33)", "[1900-3X](https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/tests/src/Kernel/EdtfUtilsTest.php#L31)", and "[190X-5X-8X](https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/tests/src/Kernel/EdtfUtilsTest.php#L35)" should validate, but I don't see where the spec allows those dates. https://pypi.org/project/edtf-validate/ doesn't validate the last two, but does validate the first one. I'm confused!

**Comment by seth-shaw-unlv** [comment] 2021-08-31 15:00
So, it is possible that the library only supports levels 0 and 1 of EDTF; placing unspecified digits at any point and sub-year groupings (like 30 for summer in the southern hemisphere) are level 2 features.

**Comment by mjordan** [comment] 2021-08-31 15:19
Code suggests it's [supposed](https://github.com/unt-libraries/edtf-validate/blob/master/edtf_validate/valid_edtf.py#L537-L566) to validate against level 2. I'll open an issue to ask.

**Comment by seth-shaw-unlv** [comment] 2021-08-31 15:32
I wouldn't get too hung up on level 2 support. If it is passing the valid level 0 and 1, run with it. That will cover 80%+ of the cases.

**Comment by mjordan** [comment] 2021-09-02 05:17
Workbench now uses https://pypi.org/project/edtf-validate/ to validate dates. I've opened https://github.com/unt-libraries/edtf-validate/issues/33 (mainly for my own edification) and will wait to hear back before closing this issue.

**Comment by mjordan** [comment] 2021-11-08 15:16
The edtf-validate library is working as intended.

**Closed by mjordan** 2021-11-08 15:16 UTC
Labels: Input data validation
