### ISSUE TITLE
HTML displays as code until node is opened and saved

### ISSUE THREAD

**Issue by myoungbe** [mjordan/islandora_workbench#367] opened 2021-12-16 16:12 UTC
I've observed that formatted text fields initially show HTML as code, but when I open and save the node with the problem (even if I don't touch that field), it then displays correctly. I've included a screenshot to show what I see before editing the node.

Drupal is 9.4.0-dev, and I am running the latest version of Workbench.

![Screen Shot 2021-11-30 at 16 36 40](https://user-images.githubusercontent.com/88156719/146407560-74570cf6-a999-4ef0-8fe3-567f38eda599.png)

**Comment by seth-shaw-unlv** [comment] 2021-12-16 16:42
Generally speaking, when ingesting into text fields you need to set the format property (e.g. 'basic_html') or else Drupal will encode the characters to be displayed as plain text.

My guess is that the field is being saved without a format property which displays the characters, but once you edit the node Drupal will populate that format property with the default (usually 'basic_html') which will then render properly when viewed again. (This happens with the Migrate API as well.)

**Comment by mjordan** [comment] 2021-12-16 17:10
Thanks @seth-shaw-unlv. Issue #328 is relevant here. I will see what's involved in resolving it (to at least provide a warning) or whether it is possible to set the format property via REST.

**Comment by dara2** [comment] 2022-09-09 19:00
Hi @mjordan ! I wanted to check in and see where this falls in the roadmap?

**Comment by mjordan** [comment] 2022-09-11 15:18
I've confirmed that, unfortunately, updating/saving the node via REST after adding the field with markup has no effect. This means there may be no (simple, at least) way of having these fields render as intended other than resaving them manually using the standard Drupal edit form. I'll continue to try to figure out how the Drupal GUI does this and if we can trigger it via REST somehow. In the meantime, I don't have an ETA for resolving this.

**Comment by mjordan** [comment] 2023-05-01 18:40
@rosiel the best I can come up with is that if there is a field in a CSV row that contains markup, Workbench programmatically logs into the (GUI) edit form after the node has been created and saves the form. This will simulate a human using the add/edit form to save the node and *should* work around the problem I've identified above. I would be open to alternative approaches to resolving this but given that it appears there is something specific about saving using the GUI, I'm not sure what other options we have.

**Comment by rosiel** [comment] 2023-05-01 19:18
I am operating under the assumption (please correct me if I'm wrong) that the Migrate API can do this kind of field properly, because it saves the `format` part of the field along with the `value` (at least, if you set it up right!). It really looks like Workbench is treating formatted text fields like plain text fields, and not sending the `format`, though a `format` gets populated to a default value when a human opens the edit form because widgets do defaults but APIs do not. (again, correct me if I'm off the mark.)

**Comment by mjordan** [comment] 2023-05-01 19:23
My understanding was that, from Seth's comment above, Migrate also didn't save enough info to trigger the output filter. Maybe that's different now. But, if we need to change workbench to push up a `format` with the field content, we can do that. Workbench as access to the field's configuration so it should not be necessary for the user to do anything else - detecting the field's `format` can be done automatically and all field instances created can get that value applied to them.

**Comment by mjordan** [comment] 2023-05-02 03:11
@rosie I have just confirmed that if provided with a text filter value (e.g. `full_html`), the field is populated  as expected, with the markup enabled. This is good news! 

But it raises a couple questions:

1. AFAICT Drupal's text formats defined at `admin/config/content/formats` are not associated with a given field's configuration; in other words, these options show up in the CRUD form for a given field by virtue solely by virtue of a field having a type of "formatted". Therefore, Workbench can't get any default text format setting for a field other than the default format, which is the first format listed on the page cited above.
2. There is no REST endpoint for text formats. This means that Workbench can't introspect Drupal to determine the "default" text format. The formats that seem to be configured out of the box are `full_html`, `basic_html`, and `restricted_html`.
3. Since there is no default text format, and no per-field configuration that defines available text formats, we will need to set a global default (for example, `basic_html`) or allow the user to define in config a field:format mapping, which Workbench can apply to each field.  Or, alternatively, provide a default text format of `basic_html` and also provide both a config option to override the text format for all fields, and also a config setting to define a specific field:format configuration.

Maybe I can ask for input in the slack channel to see what approach people prefer?

**Comment by mjordan** [comment] 2023-05-02 03:28
I've just attempted to populate a formatted field with a `format` of "foo" to see what happens. Creation fails with a 422 error accompanied by the message ""Unprocessable Entity: validation failed.\\nfield_description_long.0.format: The value you selected is not a valid choice." So while there's no way to validate the text format machine names during `--check` for the reasons I provide above, at least Drupal prevents nodes from being created with invalid text format names.

**Comment by mjordan** [comment] 2023-05-03 14:53
New config settings added in [bc47455](https://github.com/mjordan/islandora_workbench/commit/bc474556308e38731bff6cc34cefe34911acd742) that will need to be documented:

```
text_output_id: full_html # default is basic_html
```
```
field_text_output_ids:
- field_foo: restricted_html
- field_bar: basic_html
```

**Comment by mjordan** [comment] 2023-05-04 03:23
OK, this appears to be working as intended. I'm going to write some unit tests to make sure the new 'format` property, which is a bit of work, but I think/hope that's all that will be left before this is ready for field testing.

**Comment by mjordan** [comment] 2023-05-04 14:55
As for docs, I think adding a section "Text fields with markup" immediately after https://mjordan.github.io/islandora_workbench_docs/fields/#text-fields would be sensible.

**Comment by rosiel** [comment] 2023-05-04 16:59
I'm testing, and your changes seem to have no effect. 
* I checked out the issue_367 branch
* I set up a small test with <a> tags
* I tried without any changes to config.yml; and then with `text_output_id: full_html`, and then with `field_text_output_ids` as above.
* The <a> tags are still showing up as tags when I load the node.
I have a sneaking feeling I'm forgetting something. There isn't a workbench or python cache to clear?

**Comment by mjordan** [comment] 2023-05-04 17:38
Maybe deleting the __pychache__ folder? But I have not had to do that in the past when changing branches.

Obvious question, but does a `git log` show the "WIP on #367" commits?

Also, I've only tested locally using `create` tasks but it should work with `update` as well.

**Comment by mjordan** [comment] 2023-05-04 17:43
I've just fetched origin and checked out that branch on our local production instance and all the code is there. We don't use any formatted fields in our IR (that I know of) so i can't test at the moment though.

**Comment by mjordan** [comment] 2023-05-04 18:31
Just did a quick test creating a `page` and the body renders as intended:

![image](https://user-images.githubusercontent.com/403918/236296161-1e848c87-ced9-4e50-a71f-cf32f639141d.png)


Here's my config:

```
task: create
host: https://summit.sfu.ca
username: xxx
password: xxx
content_type: page
nodes_only: true
allow_missing_files: true
input_csv: issue_367.csv
```

and my CSV:

```
id,title,body
01,Test issue 367 page,Hi <a href="https://www.lib.sfu.ca">there</a>
```

**Comment by rosiel** [comment] 2023-05-04 19:38
Ah - I tested `content_type: page` (and changed the column header to `body`) and my ingest worked; the links rendered nice like yours. But it doesn't happen when using the `field_abstract` in `repository_item`.

**Comment by mjordan** [comment] 2023-05-04 20:12
Hm. Let me look into that. I am detecting that a field is "formatted" by the presence of `"module": "text"` in its "storage" configuration... sorry to delve into the plumbing here but I wonder if that pattern is sufficient or if I need to be checking for something else. Let me investigate. Thanks for the specifics, they will be useful.

**Comment by mjordan** [comment] 2023-05-04 23:09
@rosiel I am able to replicate what you describe using field_abstract. I am going to investigate. Thanks for testing!

**Comment by mjordan** [comment] 2023-05-05 14:58
Thanks - I've changed the code so that it checks to see if the `field_type` value in the config data starts with "text". This is a cleaner way of checking than what I had started with. Thanks for observing that pattern. 

Please pull in the update and try again.

Buuuut.... in the ISLE "demo" setup, even though the "Abstract" field has a type of "Text (formatted, long)":

![image](https://user-images.githubusercontent.com/403918/236489208-d7c1a9b3-5006-4527-94af-0191c500e9aa.png)

the `field_type` of `field_abstract` is "string_long", not what I expected given the pattern you observe above. Also, I'm logged in as admin and in the node add/edit form don't see any widget for selecting the text format:

![image](https://user-images.githubusercontent.com/403918/236490881-196df4a1-d4ef-4726-bb8b-9cca932b2c51.png)

Here's the field's raw config JSON (field_type is at the end): `{'uuid': '44183c63-3fb1-453d-a257-ee946b1677ef', 'langcode': 'en', 'status': True, 'dependencies': {'config': ['field.storage.node.field_abstract', 'node.type.islandora_object']}, 'id': 'node.islandora_object.field_abstract', 'field_name': 'field_abstract', 'entity_type': 'node', 'bundle': 'islandora_object', 'label': 'Abstract', 'description': '', 'required': False, 'translatable': True, 'default_value': [], 'default_value_callback': '', 'settings': [], 'field_type': 'string_long'}`

So what I take from this example is that even though my Abstract field declares in its GUI config settings that it has a type of "Text (formatted, long)", that label is misleading. Got to love Drupal.

**Comment by rosiel** [comment] 2023-05-05 17:19
I see you are using the Install Profile. Its abstract field is not formatted text (while the one in the Starter Site is formatted text). I am very confused as to why it shows up in the GUI as "Text (formatted, long)" since that is incorrect.

So I did a little grep and found that the **field.storage** of that field says it's `text_long` while the **field.field** configuration declares it `string_long`. 

This seems like the kind of thing that would happen when changing values directly in the yaml. I'll only soapbox for a second, but this is why I'm adamant about using the GUI when altering the Starter Site.

Anyway... field.field.node.islandora_object.field_table_of_contents.yml and field.storage.node.field_table_of_contents.yml both agree that field is formattable text.

**Comment by mjordan** [comment] 2023-05-05 17:41
Thanks for the background and further digging into the Drupal plumbing. I'm satisfied that checking the `field_type` (currently the code does it in the configuration settings, not the storage settings - but they should align unless there are any shenanigans - soapbox acknowledged). If that sounds OK to you, I'd like to merge this branch and I can document it. Sound OK?

**Comment by rosiel** [comment] 2023-05-05 19:23
Tested [e087e18](https://github.com/mjordan/islandora_workbench/commit/e087e1885606521ca2d8e87b50c03adf5f793384) and it worked for me. I'm happy for this to go through.

**Comment by mjordan** [comment] 2023-05-05 20:49
Merged into `main`. Docs are at https://mjordan.github.io/islandora_workbench_docs/fields/#text-fields-with-markup.

FYI, at the last minute I changed the config settings to be `text_format_id` and `text_format_ids` since they are clearer than the ones I originally came up with.

Thanks to everyone who helped with this new feature, especially @rosiel for bumping me on it and for testing.

**Closed by mjordan** 2023-05-05 20:49 UTC
Labels: limitation of dependency
